### PR TITLE
Aggegate bonded - Failure_Core_Future_Deadline

### LINKED ISSUE #1490: Aggegate bonded - Failure_Core_Future_Deadline
Steps:

1. Change system clock +1h
2. Try to send aggregate bonded transaction (for example multisig)

Result: Announcing hash lock failes with error "Failure_Core_Future_Deadline":

image

Questions:

1) Why Hash lock transaction deadline is set to 6 hours? Hash lock is confirmed immediately. Why it has 6h instead of 2h like a normal transaction?

2) When the user operating system clock is ahead 1minute (or node clock 1minute behind) the user gets an error as above. I assume here that the max deadline for the hash lock is 6h but it seems correct assumption.

3) Wouldn't better to use node time (/node/time) instead of local user time?

### PR DESCRIPTION
**Pull request by bassemmagdy**
fixes #1490

### CODE REVIEW

**Comment by cryptoBeliever** [comment]
@bassemmagdy looks like the number of API calls to the /time endpoint is too big. Please check video:
https://share.getcloudapp.com/BluxeB7B

Maybe wallet should have only time synchronization periodically called like once per minute?

**Comment by yilmazbahadir** [comment]
Can we just call the time api on the connected node manually, get the server time and hold the time difference in the state in milliseconds and create the deadline by using that difference when constructing the transaction?

**Comment by bassemmagdy** [comment]
do you mean we create we keep the deadlines objects in store till we need them in transaction building?

**Comment by bassemmagdy** [comment]
update in #1713

**Pull request closed without merging**
