### PR TITLE
fix: metadata non-ascii text update failure, views refresh issue, det…

### LINKED ISSUE #1837: Namespace/mosaic metadata views - problem with updating
Steps (metadata creation):
1. Create namespace
2. Add metadata to created namespace
3. Wait for transaction confirmation (without switching view)

Result: After transaction confirmation, new metadata is not available to view. You have to switch views and go back to see new metadata.

Steps (metadata edition):
1. Edit existing namespace metadata value
2. Wait for transaction confirmation (without switching view)

Result: After transaction confirmation, we can still see the old metadata value. You have to switch views and go back to see the new value.

Video: https://share.getcloudapp.com/bLuxNzwN

The same problem is with the creation/edition of mosaic metadata.

### PR DESCRIPTION
**Pull request by yilmazbahadir**
fixes #1837 and #1838 

### What's the fix?
* metadata non-ascii text update failure
* updated to `symbol-sdk v2.0.0`
* metadata views refresh issue
* details view fixed
* added unit tests for account, namespace and metadata transaction detail views

### CODE REVIEW

**Comment by Jaguar0625** [comment]
@0x6861746366574 - should we add regression tests for these changes?

**Review by cryptoBeliever — APPROVED** [review]

**Comment by cryptoBeliever** [comment]
Forgot to comment here. Tested (for account/namespace/mosaic) change and it looks correct:
- edit of metadata (various cases - editing when the previous value was ASCI/NON-ASCII, and new value non-ASCII/ASCII characters)
- adding new metadata
- problems with updating reported in https://github.com/symbol/desktop-wallet/issues/1837
- improvements for transaction details reported in https://github.com/symbol/desktop-wallet/issues/1838
Seems fine from my side.

**Comment by 0x6861746366574** [comment]
> @0x6861746366574 - should we add regression tests for these changes?

Yes.

**Review by Jaguar0625 — DISMISSED** [review]

**Review by Jaguar0625 — DISMISSED** [review]

**Review by Jaguar0625 — DISMISSED** [review]

**Comment by yilmazbahadir** [comment]
Sorry @Jaguar0625 for the stale reviews, we were waiting for the community to get all the translations confirmed, only Korean is yet to be confirmed now, we'll wait until tomorrow and proceed regardless. @cryptoBeliever can approve the PR for the translations to proceed to merge.

**Review by Jaguar0625 — APPROVED** [review]

**Review by cryptoBeliever — APPROVED** [review]

**Pull request merged**
